### ISSUE TITLE
change importer to support '~'

### ISSUE THREAD

**Issue by ntswor** [anarh/node-sass-import#16]
Currently I have the problem that the importer is not supporting '~' within the import path.
I used this so that my IDE (webstorm) recognizes the imports correctly.
Best thing would be if the importer either ignores (strips) it or uses it directly as a reference to node_modules.

working but not recognized as correct path from the IDE:
`@import 'bootstrap/scss/bootstrap';`
not working but correct path:
`@import '~bootstrap/scss/bootstrap';`

**Comment by anarh** [comment]
Hey @ntswor can you elaborate a bit? I'm trying to wrap my head around the need for the '~'. Perhaps is there a way for me to write a plugin for webstorm to look in the node_modules directory as well for these specific cases if the component is listed in the package.json?

**Comment by btpoe** [comment]
This feature is built into webpack. For that reason, it's gaining popularity. It's also nice to have the option to use the `~` to explicitly say "this `@import` is coming from node_modules"

**Comment by anarh** [comment]
@import should always come from node_modules. Just like npm. That's the existing behavior of this component.
