### ISSUE TITLE
Import script should consider looking at the "style" and "sass" declarations 

### ISSUE THREAD

**Issue by jrharshath** [anarh/node-sass-import#4]
Most front-end npm pacakges use the "main" field in their package.json to point to their main JS file. The css "entry point" us usually "style", as used by [bootstrap](https://github.com/twbs/bootstrap/blob/master/package.json) or "style" as well as "sass", as used by [bootstrap-sass](https://github.com/twbs/bootstrap-sass/blob/master/package.json).

**Comment by anarh** [comment]
Hey @jrharshath, looking into this now.

**Comment by jrharshath** [comment]
I implemented an import function a la yours.. It's here:

https://gist.github.com/jrharshath/73a84079398422de715df4433d763abc

**Comment by anarh** [comment]
Would love to incorporate your change here as well. I wish there was an agreed standard for which field name the community wants to use for entry .less, .scss, or .css files. That way it'd be pretty straightforward and can be even implemented within the npm module resolver itself.

**Comment by jrharshath** [comment]
True. I personally think that the `style` field is a good candidate for style-related entry points. 

However, the single entry-point field approach fails when there are multiple version of entrypoints (css, less, scss). In that case, I advocate that the project use `css`, `less` or `scss` as their entry point fields for each versions. Projects like this (`node-sass-import`) should look for `scss` first, and then for `style`.

What do you think?
