### ISSUE TITLE
Need to be able to import local scss files as well.

### ISSUE THREAD

**Issue by jrharshath** [anarh/node-sass-import#5]
Importing something like `@import 'styles/my_partial_1.css';` fails with an error that reads `Error: Cannot find module 'styles/my_partial_1.css' from <cwd>`.

**Comment by anarh** [comment]
Hey @jrharshath, I should have a solution later this week for this. Thanks!

**Comment by anarh** [comment]
Also, @jrharshath have you tried this way @import './styles/my_partial_1.css'. Take note of the './' in front of "styles/"

**Comment by jrharshath** [comment]
I can't say that I remember trying prefixing local paths with "./", but I implemented my own function for now like yours:

https://gist.github.com/jrharshath/73a84079398422de715df4433d763abc

**Comment by anarh** [comment]
@jrharshath looks good. Regarding the "./" for local files, I wanted to follow the npm convention. Anything with a "./" is local and any path without the "./" is assumed to be an npm module that is fetched from the node_modules directory. I'll go ahead and close this open issue.

**Comment by jrharshath** [comment]
+1 for following npm convention about local paths. Do local paths necessarily have to start with a `./`, or is a `../` fine too?
